### ISSUE TITLE
test problem

### ISSUE THREAD

**Issue by Victoria2333** [shaohua0116/Relation-Network-Tensorflow#11]
when i run python evaler.py --dataset_path Sort-of-CLEVR_default --model rn --checkpoint_path train_dir/baseline-default-Sort-of-CLEVR_default_lr_0.00025-20170819-213535/model-10001
it cannot start the inference and evaluation,the errors are like this:
2017-09-06 23:04:15.889399: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1052] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 660, pci bus id: 0000:01:00.0, compute capability: 3.0)
[2017-09-06 23:04:16,316] Using Model class : <class 'model_rn.Model'>
[2017-09-06 23:04:16,318] CONV
[2017-09-06 23:04:16,432] CONV/g_theta
[2017-09-06 23:04:20,278] f_phi
[2017-09-06 23:04:20,335] Successfully loaded the model.
WARNING:tensorflow:From evaler.py:96: get_or_create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.get_or_create_global_step
2017-09-06 23:04:20.338655: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1052] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 660, pci bus id: 0000:01:00.0, compute capability: 3.0)
[2017-09-06 23:04:20,407] Checkpoint path : train_dir/baseline-default-Sort-of-CLEVR_default_lr_0.00025-20170819-213535/model-10001
[2017-09-06 23:04:20,407] dataset: Sort-of-CLEVR_default
2017-09-06 23:04:20.725816: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key f_phi/fully_connected_2/weights not found in checkpoint
2017-09-06 23:04:20.726046: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key f_phi/fully_connected_2/weights not found in checkpoint
	 [[Node: save/RestoreV2_37 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_37/tensor_names, save/RestoreV2_37/shape_and_slices)]]
2017-09-06 23:04:20.726102: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key CONV/conv_4/BatchNorm/beta not found in checkpoint
2017-09-06 23:04:20.728558: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key CONV/conv_1/BatchNorm/beta not found in checkpoint
2017-09-06 23:04:20.731861: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key CONV/conv_3/w not found in checkpoint
2017-09-06 23:04:20.732235: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key f_phi/fully_connected_2/biases not found in checkpoint
2017-09-06 23:04:20.732289: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key CONV/conv_4/BatchNorm/gamma not found in checkpoint
2017-09-06 23:04:20.734357: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key CONV/conv_3/biases not found in checkpoint
2017-09-06 23:04:20.734468: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key CONV/conv_1/BatchNorm/gamma not found in checkpoint
2017-09-06 23:04:20.736531: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key CONV/conv_4/BatchNorm/moving_mean not found in checkpoint
2017-09-06 23:04:20.737279: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key f_phi/fully_connected_1/weights not found in checkpoint
2017-09-06 23:04:20.739398: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key CONV/conv_3/BatchNorm/moving_variance not found in checkpoint
2017-09-06 23:04:20.741029: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key CONV/conv_1/BatchNorm/moving_variance not found in checkpoint
2017-09-06 23:04:20.742882: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key f_phi/fully_connected_1/biases not found in checkpoint
2017-09-06 23:04:20.743091: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key CONV/conv_1/BatchNorm/moving_mean not found in checkpoint
2017-09-06 23:04:20.745361: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key CONV/conv_3/BatchNorm/moving_mean not found in checkpoint
2017-09-06 23:04:20.745434: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key CONV/conv_1/biases not found in checkpoint
2017-09-06 23:04:20.747760: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key f_phi/fully_connected/weights not found in checkpoint
2017-09-06 23:04:20.747760: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key CONV/conv_1/w not found in checkpoint
2017-09-06 23:04:20.750858: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key CONV/conv_3/BatchNorm/gamma not found in checkpoint
2017-09-06 23:04:20.751412: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key f_phi/fully_connected/biases not found in checkpoint
2017-09-06 23:04:20.752404: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key CONV/conv_4/BatchNorm/moving_variance not found in checkpoint
2017-09-06 23:04:20.754160: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key CONV/conv_2/BatchNorm/beta not found in checkpoint
2017-09-06 23:04:20.755551: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key CONV/g_theta/fully_connected_3/weights not found in checkpoint
2017-09-06 23:04:20.755632: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key CONV/conv_3/BatchNorm/beta not found in checkpoint
2017-09-06 23:04:20.755763: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key CONV/conv_4/biases not found in checkpoint
2017-09-06 23:04:20.758080: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key CONV/conv_2/BatchNorm/gamma not found in checkpoint
2017-09-06 23:04:20.760821: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key CONV/conv_2/w not found in checkpoint
2017-09-06 23:04:20.762303: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key CONV/conv_4/w not found in checkpoint
2017-09-06 23:04:20.762356: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key CONV/g_theta/fully_connected_3/biases not found in checkpoint
2017-09-06 23:04:20.763147: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key CONV/conv_2/BatchNorm/moving_mean not found in checkpoint
2017-09-06 23:04:20.763228: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key CONV/conv_2/biases not found in checkpoint
2017-09-06 23:04:20.767768: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key CONV/g_theta/fully_connected_2/weights not found in checkpoint
2017-09-06 23:04:20.767895: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key CONV/conv_2/BatchNorm/moving_variance not found in checkpoint
2017-09-06 23:04:20.774584: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key CONV/g_theta/fully_connected/biases not found in checkpoint
2017-09-06 23:04:20.775900: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key CONV/g_theta/fully_connected_1/biases not found in checkpoint
2017-09-06 23:04:20.776379: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key CONV/g_theta/fully_connected_2/biases not found in checkpoint
2017-09-06 23:04:20.776488: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key CONV/g_theta/fully_connected/weights not found in checkpoint
2017-09-06 23:04:20.777465: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key CONV/g_theta/fully_connected_1/weights not found in checkpoint
Traceback (most recent call last):
  File "evaler.py", line 223, in <module>
    main()
  File "evaler.py", line 220, in main
    evaler.eval_run()
  File "evaler.py", line 123, in eval_run
    self.saver.restore(self.session, self.checkpoint_path)
  File "/home/han/tensorflow/_python_build/tensorflow/python/training/saver.py", line 1560, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/han/tensorflow/_python_build/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/han/tensorflow/_python_build/tensorflow/python/client/session.py", line 1118, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/han/tensorflow/_python_build/tensorflow/python/client/session.py", line 1315, in _do_run
    options, run_metadata)
  File "/home/han/tensorflow/_python_build/tensorflow/python/client/session.py", line 1334, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key f_phi/fully_connected_2/weights not found in checkpoint
	 [[Node: save/RestoreV2_37 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_37/tensor_names, save/RestoreV2_37/shape_and_slices)]]
	 [[Node: save/RestoreV2_4/_73 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_156_save/RestoreV2_4", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op u'save/RestoreV2_37', defined at:
  File "evaler.py", line 223, in <module>
    main()
  File "evaler.py", line 217, in main
    evaler = Evaler(config, dataset_test)
  File "evaler.py", line 109, in __init__
    self.saver = tf.train.Saver(max_to_keep=100)
  File "/home/han/tensorflow/_python_build/tensorflow/python/training/saver.py", line 1140, in __init__
    self.build()
  File "/home/han/tensorflow/_python_build/tensorflow/python/training/saver.py", line 1172, in build
    filename=self._filename)
  File "/home/han/tensorflow/_python_build/tensorflow/python/training/saver.py", line 688, in build
    restore_sequentially, reshape)
  File "/home/han/tensorflow/_python_build/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/han/tensorflow/_python_build/tensorflow/python/training/saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "/home/han/tensorflow/_python_build/tensorflow/python/ops/gen_io_ops.py", line 991, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/home/han/tensorflow/_python_build/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/han/tensorflow/_python_build/tensorflow/python/framework/ops.py", line 3046, in create_op
    op_def=op_def)
  File "/home/han/tensorflow/_python_build/tensorflow/python/framework/ops.py", line 1604, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Key f_phi/fully_connected_2/weights not found in checkpoint
	 [[Node: save/RestoreV2_37 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_37/tensor_names, save/RestoreV2_37/shape_and_slices)]]
	 [[Node: save/RestoreV2_4/_73 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_156_save/RestoreV2_4", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
And i also tried the other file(model-1.data-00000-of-00001,model-1.index,model-1.meta),it seems to occur the same problem,and when i omitted the checkpoint path,it occurs odd results:
[2017-09-06 23:11:59,187] Average accuracy of non-relational questions: 0.488599348534%
[2017-09-06 23:11:59,187] Average accuracy of relational questions: 12.1654501217%
[2017-09-06 23:11:59,187] Average accuracy: 5.17073170732%
[2017-09-06 23:11:59,187] Evaluation complete.
Please give me some tips about this,thank you~

**Comment by Victoria2333** [comment]
It seemed like the model cannot be reloaded correctly, i don't know how to solve it,could you help me??
Looking forward to your reply~~~

**Comment by shaohua0116** [comment]
Please note that there are two different models, which are the baseline model (*baseline*) and the relation network (*rn*) and they have different architectures. Based on the command you provided, you are trying to load the checkpoint of a trained baseline model to restore a relation network which causes the error. Just change `--model rn` to `--model baseline` and it should work just fine.
