### ISSUE TITLE
Problem with trainer.py

### ISSUE THREAD

**Issue by ClaudeCoulombe** [shaohua0116/Relation-Network-Tensorflow#2]
Then when I try python trainer.py it raises ValueError('num_outputs should be int or long, got %s.', num_outputs) ValueError: ('num_outputs should be int or long, got %s.', 10). 

It seems not related to the generation process that is working now

I've checked and num_outputs 10 is <class 'numpy.int64' at 0x102e01418> a NumPy type int64 but the TensorFlow library is expecting regular int or long type. 

Traceback (most recent call last):
  File "trainer.py", line 242, in <module>
    main()
  File "trainer.py", line 235, in main
    dataset_train, dataset_test)
  File "trainer.py", line 57, in __init__
    self.model = Model(config)
  File "/Users/claudecoulombe/git/Relation-Network-Tensorflow/model_rn.py", line 47, in __init__
    self.build(is_train=is_train)
  File "/Users/claudecoulombe/git/Relation-Network-Tensorflow/model_rn.py", line 131, in build
    logits = f_phi(g, scope='f_phi')
  File "/Users/claudecoulombe/git/Relation-Network-Tensorflow/model_rn.py", line 127, in f_phi
    fc_3 = fc(fc_2, n, activation_fn=None, name='fc_3')
  File "/Users/claudecoulombe/git/Relation-Network-Tensorflow/ops.py", line 42, in fc
    output = slim.fully_connected(input, output_shape, activation_fn=activation_fn)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 177, in func_with_args
    return func(*args, **current_args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1386, in fully_connected
    raise ValueError('num_outputs should be int or long, got %s.', num_outputs)
ValueError: ('num_outputs should be int or long, got %s.', 10)

My configuration:

Python 3.6.0a2
TensorFlow 1.0.1
NumPy 1.12.1
PIL 1.1.7
matplotlib 1.5.1
h5py 2.7.0
progressbar 3.30.2

Is it possible that the TensorFlow version 1.0.1 which differs from the prerequisite 1.0.0 could explain the problem?

**Comment by shaohua0116** [comment]
Thanks for your the detailed information. I tried to reproduce the error and found that it's the problem of type conversion. Simply changing the line 42 of ops.py to ```output = slim.fully_connected(input, int(output_shape), activation_fn=activation_fn)``` can resolve it.

**Comment by ClaudeCoulombe** [comment]
Nice! I'm now able to load the model and start training it. Your suggestion is a lot more elegant than the patch I've done directly in the TensorFlow library. Good we progress...

**Comment by idibidiart** [comment]
Is there a need to update the code in this repo? Or is trainer.py an external thing?

**Comment by shaohua0116** [comment]
Thanks for the suggestion. I just updated ops.py.
