### ISSUE TITLE
Problem during training...

### ISSUE THREAD

**Issue by ClaudeCoulombe** [shaohua0116/Relation-Network-Tensorflow#3]
Now, I've got an error with a None argument, in fact fetch is None at line 162 in trainer.py. It seems to be an error with the model but I'm not sure... also step is 0 ??? it looks a bit strange to me.

> python trainer.py
[2017-06-24 20:09:54,919] Reading ./datasets/Sort-of-CLEVR_default/data.hy ...
[2017-06-24 20:09:54,929] Reading Done: ./datasets/Sort-of-CLEVR_default/data.hy
[2017-06-24 20:09:54,929] Reading ./datasets/Sort-of-CLEVR_default/data.hy ...
[2017-06-24 20:09:54,930] Reading Done: ./datasets/Sort-of-CLEVR_default/data.hy
[2017-06-24 20:09:54,930] Train Dir: ./train_dir/rn-default-Sort-of-CLEVR_default_lr_0.00025-20170624-200954
[2017-06-24 20:09:54,930] input_ops [inputs]: Using 8000 IDs from dataset
[2017-06-24 20:09:55,082] input_ops [inputs]: Using 2000 IDs from dataset
[2017-06-24 20:09:56,609] Using Model class : <class 'model_rn.Model' at 0x10ebe18d8>
[2017-06-24 20:09:56,614] CONV
[2017-06-24 20:09:56,984] CONV/g_theta
[2017-06-24 20:10:06,848] f_phi
[2017-06-24 20:10:07,013] Successfully loaded the model.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
[2017-06-24 20:11:30,513] dataset: Sort-of-CLEVR_default, learning_rate: 0.000250
[2017-06-24 20:11:30,514] Training Starts!
{'a': <tf.Tensor 'shuffle_batch:0' shape=(16, 10) dtype=float32>,
 'id': <tf.Tensor 'shuffle_batch:1' shape=(16,) dtype=string>,
 'img': <tf.Tensor 'shuffle_batch:2' shape=(16, 128, 128, 3) dtype=float32>,
 'q': <tf.Tensor 'shuffle_batch:3' shape=(16, 11) dtype=float32>}
Traceback (most recent call last):
  File "trainer.py", line 242, in <module>
    main()
  File "trainer.py", line 239, in main
    trainer.train()
  File "trainer.py", line 130, in train
    self.run_single_step(self.batch_train, step=s, is_train=True)
  File "trainer.py", line 162, in run_single_step
    fetch, feed_dict=self.model.get_feed_dict(batch_chunk, step=step)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 952, in _run
    fetch_handler = _FetchHandler(self._graph, fetches, feed_dict_string)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 408, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 230, in for_fetch
    return _ListFetchMapper(fetch)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 337, in __init__
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 337, in <listcomp>
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 227, in for_fetch
    (fetch, type(fetch)))
TypeError: Fetch argument None has invalid type <class 'NoneType' at 0x10022ce60>
>

**Comment by shaohua0116** [comment]
The cause of this issue is that the library *tfplot* is not installed on your machine. I fixed the problem by handling the exception in a previous commit. Can you clone the newest one and try again?However, Installing to visualize the training is recommended. You can install with this command ```pip install git+https://github.com/wookayin/tensorflow-plot.git@master```.

**Comment by ClaudeCoulombe** [comment]
You're quite reactive for a Saturday!!! Thanks a lot! 

Eventually you should add tensorflow-plot in the Prerequisites. 

Anyway, after cloning the newest version of the repo, generate the data and install /tensorflow-plot

`pip3 install git+https://github.com/wookayin/tensorflow-plot.git@master`

I've got a different error... this time... It seems not like `tensorflow-plot` at all... ;)

Hint: `model_rn.py`, line 137, then after a method in `figure.py` expected 2 arguments, got 3

The complete trace below...

------------------------------

> python trainer.py
[2017-06-24 23:26:19,308] Reading ./datasets/Sort-of-CLEVR_default/data.hy ...
[2017-06-24 23:26:19,310] Reading Done: ./datasets/Sort-of-CLEVR_default/data.hy
[2017-06-24 23:26:19,311] Reading ./datasets/Sort-of-CLEVR_default/data.hy ...
[2017-06-24 23:26:19,311] Reading Done: ./datasets/Sort-of-CLEVR_default/data.hy
[2017-06-24 23:26:19,312] Train Dir: ./train_dir/rn-default-Sort-of-CLEVR_default_lr_0.00025-20170624-232619
[2017-06-24 23:26:19,313] input_ops [inputs]: Using 8000 IDs from dataset
[2017-06-24 23:26:19,519] input_ops [inputs]: Using 2000 IDs from dataset
[2017-06-24 23:26:21,218] Using Model class : <class 'model_rn.Model' at 0x1107576b8>
[2017-06-24 23:26:21,223] CONV
[2017-06-24 23:26:21,833] CONV/g_theta
[2017-06-24 23:26:35,401] f_phi
[2017-06-24 23:26:35,648] Successfully loaded the model.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
[2017-06-24 23:28:20,912] dataset: Sort-of-CLEVR_default, learning_rate: 0.000250
[2017-06-24 23:28:20,912] Training Starts!
{'a': <tf.Tensor 'shuffle_batch:0' shape=(16, 10) dtype=float32>,
 'id': <tf.Tensor 'shuffle_batch:1' shape=(16,) dtype=string>,
 'img': <tf.Tensor 'shuffle_batch:2' shape=(16, 128, 128, 3) dtype=float32>,
 'q': <tf.Tensor 'shuffle_batch:3' shape=(16, 11) dtype=float32>}
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 82, in __call__
    ret = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tfplot/ops.py", line 61, in _render_image
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 82, in __call__
    ret = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tfplot/ops.py", line 61, in _render_image
    fig = plot_func(*args, **kwargs)
    fig = plot_func(*args, **kwargs)
  File "/Users/claudecoulombe/git/Relation-Network-Tensorflow/model_rn.py", line 137, in draw_iqa
  File "/Users/claudecoulombe/git/Relation-Network-Tensorflow/model_rn.py", line 137, in draw_iqa
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 82, in __call__
    ret = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tfplot/ops.py", line 61, in _render_image
    fig = plot_func(*args, **kwargs)
  File "/Users/claudecoulombe/git/Relation-Network-Tensorflow/model_rn.py", line 137, in draw_iqa
    fig, ax = tfplot.subplots(figsize=(6, 6))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tfplot/figure.py", line 41, in subplots
    fig, ax = tfplot.subplots(figsize=(6, 6))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tfplot/figure.py", line 41, in subplots
    fig, ax = tfplot.subplots(figsize=(6, 6))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tfplot/figure.py", line 41, in subplots
    fig.subplots = types.MethodType(mpl_figure.subplots, fig, FigureClass)
TypeError: method expected 2 arguments, got 3
W tensorflow/core/framework/op_kernel.cc:993] Internal: Failed to run py callback pyfunc_2: see error log.
    fig.subplots = types.MethodType(mpl_figure.subplots, fig, FigureClass)
TypeError: method expected 2 arguments, got 3
W tensorflow/core/framework/op_kernel.cc:993] Internal: Failed to run py callback pyfunc_5: see error log.
    fig.subplots = types.MethodType(mpl_figure.subplots, fig, FigureClass)
TypeError: method expected 2 arguments, got 3
W tensorflow/core/framework/op_kernel.cc:993] Internal: Failed to run py callback pyfunc_3: see error log.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 82, in __call__
    ret = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tfplot/ops.py", line 61, in _render_image
    fig = plot_func(*args, **kwargs)
  File "/Users/claudecoulombe/git/Relation-Network-Tensorflow/model_rn.py", line 137, in draw_iqa
    fig, ax = tfplot.subplots(figsize=(6, 6))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tfplot/figure.py", line 41, in subplots
    fig.subplots = types.MethodType(mpl_figure.subplots, fig, FigureClass)
TypeError: method expected 2 arguments, got 3
W tensorflow/core/framework/op_kernel.cc:993] Internal: Failed to run py callback pyfunc_4: see error log.
W tensorflow/core/framework/op_kernel.cc:993] Internal: Failed to run py callback pyfunc_2: see error log.
	 [[Node: IQA/Plot_0 = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], Tout=[DT_UINT8], token="pyfunc_2", _device="/job:localhost/replica:0/task:0/cpu:0"](IQA/img_unstack, IQA/q_unstack, IQA/a_unstack, IQA/Softmax_unstack)]]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1022, in _do_call
    return fn(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1004, in _run_fn
    status, run_metadata)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InternalError: Failed to run py callback pyfunc_2: see error log.
	 [[Node: IQA/Plot_0 = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], Tout=[DT_UINT8], token="pyfunc_2", _device="/job:localhost/replica:0/task:0/cpu:0"](IQA/img_unstack, IQA/q_unstack, IQA/a_unstack, IQA/Softmax_unstack)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "trainer.py", line 246, in <module>
    main()
  File "trainer.py", line 243, in main
    trainer.train()
  File "trainer.py", line 131, in train
    self.run_single_step(self.batch_train, step=s, is_train=True)
  File "trainer.py", line 163, in run_single_step
    fetch, feed_dict=self.model.get_feed_dict(batch_chunk, step=step)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Failed to run py callback pyfunc_2: see error log.
	 [[Node: IQA/Plot_0 = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], Tout=[DT_UINT8], token="pyfunc_2", _device="/job:localhost/replica:0/task:0/cpu:0"](IQA/img_unstack, IQA/q_unstack, IQA/a_unstack, IQA/Softmax_unstack)]]

Caused by op 'IQA/Plot_0', defined at:
  File "trainer.py", line 246, in <module>
    main()
  File "trainer.py", line 239, in main
    dataset_train, dataset_test)
  File "trainer.py", line 57, in __init__
    self.model = Model(config)
  File "/Users/claudecoulombe/git/Relation-Network-Tensorflow/model_rn.py", line 47, in __init__
    self.build(is_train=is_train)
  File "/Users/claudecoulombe/git/Relation-Network-Tensorflow/model_rn.py", line 147, in build
    collections=["plot_summaries"])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tfplot/summary.py", line 78, in plot_many
    **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tfplot/ops.py", line 126, in plot_many
    im = plot(plot_func, arg, name=('Plot_%d' % k), **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tfplot/ops.py", line 73, in plot
    name=name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 189, in py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/ops/gen_script_ops.py", line 40, in _py_func
    name=name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InternalError (see above for traceback): Failed to run py callback pyfunc_2: see error log.
	 [[Node: IQA/Plot_0 = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], Tout=[DT_UINT8], token="pyfunc_2", _device="/job:localhost/replica:0/task:0/cpu:0"](IQA/img_unstack, IQA/q_unstack, IQA/a_unstack, IQA/Softmax_unstack)]]

**Comment by wookayin** [comment]
Hello, I am the author of [tensorflow-plot](https://github.com/wookayin/tensorflow-plot).

First of all I suggest for you to use "```" (backticks) to include code snippets.

The essentia of the stacktrace is:
```
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tfplot/figure.py", line 41, in subplots
fig.subplots = types.MethodType(mpl_figure.subplots, fig, FigureClass)
TypeError: method expected 2 arguments, got 3
```
which occurred becuase of the library has some compatibility problem with Python 3. I will fix it soon!

/cc @shaohua0116 maybe, we can also make plot functions optional.

**Comment by ClaudeCoulombe** [comment]
Thank you for the quick answer and the `backticks` suggestion. I'm waiting the fix with patience and enthusiasm.

**Comment by wookayin** [comment]
I have fixed the bug at the commit wookayin/tensorflow-plot@e94e4c71b. Can you please try again?

Since the library is on snapshot not uploaded to pypi, make sure to force pip to reinstall the library, for example:
```
pip install --upgrade --no-deps --force-reinstall git+https://github.com/wookayin/tensorflow-plot.git@master
```

**Comment by ClaudeCoulombe** [comment]
Great! It seems to work fine now! It's training!  

Thanks to Jongwook Choi and Shao-Hua Sun. Have a good weekend!

> [2017-06-25 00:56:26,403]  [train step    1] Loss: 2.31791 Accuracy test: 6.25 Accuracy test: 6.25 (4.931 sec/batch, 3.245 instances/sec) 
> [2017-06-25 00:56:26,405] Saved checkpoint at 0

...

I will reopen this issue if necessary.
